# Site settings
title: 'Me, I’m Counting.' # Your Title
tagline: 'Nobody in Particular' # A brief tagline for your site
sidebar_image: /images/cover1.jpg

# Build settings
markdown: kramdown
highlighter: pygments
baseurl: # the subpath of your site, e.g. /blog/
